FROM unidata/nctests:base

###
# Copy over a script to provision.
###

USER root
ENV HOME /root
WORKDIR ${HOME}

COPY provision_serial_ubuntu.sh /root
RUN chmod 755 provision_serial_ubuntu.sh
RUN cd /root && ls -alh && whoami && ./provision_serial_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

USER ${CUSER}
ENV HOME /home/${CUSER}
WORKDIR ${HOME}

COPY Dockerfile.serial ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_serial_tests.sh
