version: '3.7'

services:
  regression-testing:
    image: unidata/nctests:serial
    environment:
      - USEDASH=TRUE
      - TESTPROC=100
    deploy:
      replicas: 1
    networks:
      - regressnet

networks:
  regressnet:
