FROM unidata/nctests:base32

RUN sudo apt-get install -y mpich libmpich-dev

###
# Manually install hdf4 so that we can run
# those tests as well.
###

RUN cd hdf-4.2.12 && CC=`which mpicc` ./configure --disable-static --enable-shared --disable-netcdf --disable-fortran --prefix=/usr && make -j 4 && sudo make install
RUN rm -rf hdf-4.2.12

###
# Manually install hdf5 so that we can run
# those tests as well.
###

RUN cd ${HDF5_VER} && CFLAGS="-Wno-format-security" CC=`which mpicc` ./configure --disable-static --enable-shared --disable-fortran --enable-hl --enable-parallel --prefix=/usr --with-szlib  && make -j 4 && sudo make install
RUN rm -rf ${HDF5_VER}

###
# Manually install pnetcdf so that we can
# run pnetcdf tests.
###

ENV PNC161_INSTALL /pnetcdf-installs/1.6.1

RUN cd parallel-netcdf-1.6.1 && CPPFLAGS="-fPIC" CC=`which mpicc` ./configure --prefix=${PNC161_INSTALL} --disable-fortran && make -j 4 -k && sudo make install
RUN rm -rf parallel-netcdf-1.6.1

ENV PNC170_INSTALL /pnetcdf-installs/1.7.0

RUN cd parallel-netcdf-1.7.0 && CPPFLAGS="-fPIC" CC=`which mpicc` ./configure --prefix=${PNC170_INSTALL} --disable-fortran && make -j 4 -k && sudo make install
RUN rm -rf parallel-netcdf-1.7.0

###
# Copy over the dockerfile, scripts and README.
###


COPY Dockerfile.serial ${HOME}/
# COPY run_par_tests.sh ${HOME}/

ENV PARTYPE -mpich

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test scripts on launch.
##
CMD ${HOME}/run_par_tests.sh
