serial:
  build: .
  dockerfile: Dockerfile.serial

openmpi:
  build: .
  dockerfile: Dockerfile.openmpi

mpich:
  build: .
  dockerfile: Dockerfile.mpich

serial32:
  build: .
  dockerfile: Dockerfile.serial32

openmpi32:
  build: .
  dockerfile: Dockerfile.openmpi32

mpich32:
  build: .
  dockerfile: Dockerfile.mpich32
