version: '3.7'

services:
  ubuntu_base:
    image: unidata/nctests:base
    build:
      context: .
      dockerfile: Dockerfile.base


  ubuntu_serial:
    image: unidata/nctests:serial
    build:
      context: .
      dockerfile: Dockerfile.serial
    depends_on:
     - ubuntu_base

  ubuntu_mpich:
    image: unidata/nctests:mpich
    build:
      context: .
      dockerfile: Dockerfile.mpich
    depends_on:
      - ubuntu_base



  ubuntu_base32:
    image: unidata/nctests:base32
    build:
      context: .
      dockerfile: Dockerfile.base32
