version: '3.7'

services:
  base.ubuntu:
    image: unidata/nctests:base
    build:
      dockerfile: Dockerfile.base
      context: ./

  base.serial:
    image: unidata/nctests:serial
    build:
      dockerfile: Dockerfile.serial
      context: ./
