FROM unidata/nctests:base32

###
# Copy over a script to provision.
###

COPY provision_serial_ubuntu.sh ${HOME}/
RUN chmod 755 provision_serial_ubuntu.sh
RUN ${HOME}/provision_serial_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.serial ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_serial_tests.sh
