FROM unidata/nctests:base.fedora

###
# Copy over a script to provision.
###

COPY provision_serial_fedora.sh /root/
RUN sudo ls -alh /root &&  sudo /root/provision_serial_fedora.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.serial.fedora ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_serial_tests.sh
