FROM unidata/nctests:base32

###
# Copy over a script to provision.
###

COPY provision_serial_ubuntu.sh /root/
RUN sudo ls -alh /root &&  sudo /root/provision_serial_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.serial32 ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD bash -l -e ${HOME}/run_serial_tests.sh
