FROM unidata/nctests:base

RUN sudo apt-get update &&  sudo apt-get install -y mpich libmpich-dev && sudo apt-get -y autoclean && sudo rm -rf /var/lib/apt/lists/*

###
# Copy over provisioning script.
###

COPY provision_parallel_ubuntu.sh /root/
RUN sudo ls -alh /root && sudo /root/provision_parallel_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.mpich ${HOME}/

ENV PARTYPE -mpich

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test scripts on launch.
##
CMD ${HOME}/run_par_tests.sh
