FROM docker.unidata.ucar.edu/nctests:base

###
# Copy over a script to provision.
###

USER root
COPY provision_serial_ubuntu.sh /root/
RUN ls -alh /root &&  /root/provision_serial_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.serial ${HOME}/

RUN chown -R ${CUSER}:${CUSER} ${HOME}

user ${CUSER}
##
# Run test script on launch.
##
CMD bash -l -e ${HOME}/run_serial_tests.sh
