#####
# Common stuff goes at the front,
# so that we can take advantage of the
# shared layers that docker provides.
#####
FROM ubuntu:22.04 
USER root
ENV HOME=/root
WORKDIR /root
LABEL maintainer="Ward Fisher <wfisher@ucar.edu>"

ENV NCTEST_VERSION="1.11.2 - development"

ENV VERSION_FILE=VERSION.md

###
# Set up a couple environmental variables.
###

ENV CTEST_OUTPUT_ON_FAILURE=1

ENV HDF5VER=1.14.3
ENV H5VER=1.14.3
ENV HDF5_VER=hdf5-${HDF5VER}
ENV HDF5_FILE=${HDF5_VER}.tar.bz2
ENV PNCVER=1.12.3
##
# Let the user specify the branches.
##
ENV CBRANCH=main
ENV FBRANCH=main
ENV CXXBRANCH=master
ENV PBRANCH=master
ENV NCOBRANCH=master
ENV JAVABRANCH=maint-5.x
ENV JDKVER=8
ENV MPICHVER=""
##
# Specify the locations for local mapped volumes if we want to skip git checkout.
# This will allow us to change it dynamically if we are running on Github Actions or some
# other platorm.
##
ENV C_VOLUME_MAP=/netcdf-c
ENV FORTRAN_VOLUME_MAP=/netcdf-fortran
ENV CXX4_VOLUME_MAP=/netcdf-cxx4
ENV JAVA_VOLUME_MAP=/netcdf-java

##
# Specify a working directory so that we can do a volume mount
# to capture all the output, if need be.
##

ENV WORKING_DIRECTORY=/workdir

##
# Other variables
##
ENV BITNESS=64
ENV USE_CC=gcc
ENV USE_CXX=g++

ENV RUNC=TRUE
ENV RUNF=TRUE
ENV RUNCXX=FALSE
ENV RUNP=FALSE
ENV RUNNCO=FALSE
ENV RUNJAVA=FALSE
ENV RUNCXX4=FALSE

ENV USEDASH=FALSE

ENV USEAC=FALSE
ENV USECMAKE=TRUE

ENV CREPS=1
ENV FREPS=1
ENV CXXREPS=1
ENV PREPS=1
ENV NCOREPS=1
ENV TESTPROC=""
ENV TESTPROC_FORTRAN=""
ENV CUSER=tester
ENV CUSSERPWORD=""
ENV CTEST_REPEAT=3


###
# Copy over local tarballs.
# No longer needed, all handled dynamically.
###
#COPY hdf5-1.14.3.tar.bz2 pnetcdf-1.12.3.tar.gz hdf4.3.0.tar.gz ${HOME}/


###
# Run the provision scripot.
###
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Denver
RUN apt-get update
RUN apt-get install -y tzdata

COPY provision_base_ubuntu.sh ${HOME}/
RUN chmod 755 ${HOME}/provision_base_ubuntu.sh
RUN ${HOME}/provision_base_ubuntu.sh

#####
# Configure system and environment.
#####
USER ${CUSER}
ENV HOME=/home/${CUSER}
WORKDIR ${HOME}

###
# Add the utility scripts, for portability.
###

COPY run_netcdf_tests.sh ${HOME}/
COPY run_tests.sh ${HOME}/
COPY install_hdf5.sh ${HOME}/
COPY install_mpich.sh ${HOME}/
COPY README.md ${HOME}/

RUN echo "Version:\n\tunidata/nctests ($BITNESS) :\t$NCTEST_VERSION\t$(date)" > "/home/tester/${VERSION_FILE}"

USER root
RUN chown -R tester:tester ${HOME}
USER ${CUSER}

RUN dos2unix ${HOME}/run_tests.sh
RUN dos2unix ${HOME}/run_netcdf_tests.sh 
RUN dos2unix ${HOME}/install_hdf5.sh
RUN dos2unix ${HOME}/install_mpich.sh
RUN chmod 755 ${HOME}/install_hdf5.sh
RUN chmod 755 ${HOME}/install_mpich.sh

ENTRYPOINT ["/bin/bash", "-l", "-e", "/home/tester/run_tests.sh"]