FROM unidata/nctests:base

###
# Copy over a script to provision.
###

COPY provision_serial_ubuntu.sh /root/
#RUN cd /root && ls -alh && whoami && ./provision_serial_ubuntu.sh
RUN sudo ls -alh /root &&  sudo /root/provision_serial_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.serial ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_serial_tests.sh
