FROM docker.unidata.ucar.edu/nctests:base

USER root
RUN sudo apt update && sudo apt install -y python3 && sudo apt -y autoclean && sudo rm -rf /var/lib/apt/lists/*

###
# Copy over provisioning script.
###

COPY provision_parallel_ubuntu.sh /root/
#COPY mpich-4.2.3.tar.gz /root
RUN ls -alh /root && /root/provision_parallel_ubuntu.sh

###
# Copy over the dockerfile, scripts and README.
###

COPY Dockerfile.mpich ${HOME}/

ENV USE_CC=mpicc
ENV PARTYPE=-mpich
ENV TESTTYPE=mpich

RUN chown -R ${CUSER}:${CUSER} ${HOME}

USER ${CUSER}

##
# Run test scripts on launch.
##
CMD ["bash", "-l", "-e", "/home/tester/run_tests.sh"]
