FROM unidata/nctests:base32

RUN sudo apt-get install -y libopenmpi-dev openmpi-bin

###
# Set up some symbolic links, since
# we are forced to install an old
# version of gcc/g++/gfortran
###

###
# Manually install hdf4 so that we can run
# those tests as well.
###

RUN cd hdf-4.2.12 && CC=`which mpicc` ./configure --disable-static --enable-shared --disable-netcdf --disable-fortran --prefix=/usr && make -j 4 && sudo make install
RUN rm -rf hdf-4.2.12

###
# Manually install hdf5 so that we can run
# those tests as well.
###

RUN cd ${HDF5_VER} && CC=`which mpicc` ./configure --disable-static --enable-shared --disable-fortran --enable-hl --enable-parallel --prefix=/usr --with-szlib && make -j 4 && sudo make install
RUN rm -rf ${HDF5_VER}


###
# Manually install pnetcdf so that we can
# run pnetcdf tests.
###

RUN cd parallel-netcdf-1.8.1 && CPPFLAGS="-fPIC" CC=`which mpicc` ./configure --prefix=/usr --disable-fortran && make -j 4 -k && sudo make install
RUN rm -rf parallel-netcdf-1.8.1

###
# Copy over the dockerfile, scripts and README.
###


COPY Dockerfile.serial ${HOME}/
# COPY run_par_tests.sh ${HOME}/

ENV PARTYPE -openmpi

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_par_tests.sh
