#####
# Common stuff goes at the front,
# so that we can take advantage of the
# shared layers that docker provides.
#####
#
# Base image selection:
#   ubuntu:24.04 does not publish a linux/386 manifest (Ubuntu dropped i386
#   from official Docker images). debian:bookworm is used for linux/386 because
#   Debian maintains full i386 support and package names are compatible.
#   All other platforms continue to use ubuntu:24.04.
#
#FROM ubuntu:22.04
FROM ubuntu:24.04 AS base-amd64
FROM ubuntu:24.04 AS base-arm64
FROM ubuntu:24.04 AS base-s390x
FROM debian:bookworm AS base-386

ARG TARGETARCH=amd64
FROM base-${TARGETARCH}
#FROM ubuntu:25.04
USER root
ENV HOME=/root
WORKDIR /root
LABEL maintainer="Ward Fisher <wfisher@ucar.edu>"

ENV NCTEST_VERSION="1.13.7 - Development"

ENV VERSION_FILE=VERSION.md

###
# Set up a couple environmental variables.
###

ENV CTEST_OUTPUT_ON_FAILURE=1

ENV HDF5VER=1.14.6
ENV H5VER=1.14.6
ENV H5PACKAGE=FALSE
ENV HDF5_VER=hdf5-${HDF5VER}
ENV HDF5_FILE=${HDF5_VER}.tar.bz2
ENV H5ROS3=FALSE
ENV PNCVER=1.12.3
ENV BASEDIR=/environments

# AWS-releated
ENV USES3INT=FALSE
ENV USES3SDK=FALSE
ENV S3SDKVER=main

##
# Let the user specify the branches.
##
ENV CBRANCH=main
ENV FBRANCH=main
ENV CXXBRANCH=master
ENV PBRANCH=master
ENV NCOBRANCH=master
ENV JAVABRANCH=maint-5.x
ENV JDKVER=17
ENV MPICHVER=default

##
# Specify the locations for local mapped volumes if we want to skip git checkout.
# This will allow us to change it dynamically if we are running on Github Actions or some
# other platorm.
##
ENV C_VOLUME_MAP=/netcdf-c
ENV FORTRAN_VOLUME_MAP=/netcdf-fortran
ENV CXX4_VOLUME_MAP=/netcdf-cxx4
ENV JAVA_VOLUME_MAP=/netcdf-java

##
# Specify a working directory so that we can do a volume mount
# to capture all the output, if need be.
##

ENV WORKING_DIRECTORY=/workdir

##
# Other variables
##

# TARGETARCH is automatically provided by Docker Buildx in multi-platform builds.
# Accepted values: amd64, arm64, s390x, 386 (linux/386 = 32-bit x86).
ARG TARGETARCH
ENV BITNESS=64
ENV USE_CC=gcc
ENV USE_CXX=g++


ENV RUNC=TRUE
ENV RUNF=TRUE
ENV RUNCXX=FALSE
ENV RUNP=FALSE
ENV RUNNCO=FALSE
ENV RUNJAVA=FALSE
ENV RUNCXX4=FALSE
ENV CDOCS=FALSE
ENV CDOCS_DEV=FALSE
ENV FDOCS=FALSE
ENV FDOCS_DEV=FALSE

ENV USEDASH=FALSE

ENV USE_BUILDSYSTEM=both
ENV USEAC=TRUE
ENV USECMAKE=TRUE

ENV CREPS=1
ENV FREPS=1
ENV CXXREPS=1
ENV PREPS=1
ENV NCOREPS=1
ENV TESTPROC=""
ENV TESTPROC_FORTRAN=""
ENV CUSER=tester
ENV CUSERPWORD=""
ENV CTEST_REPEAT=3


###
# Copy over local tarballs.
# No longer needed, all handled dynamically.
###
#COPY hdf5-1.14.6.tar.bz2 pnetcdf-1.12.3.tar.gz hdf4.3.0.tar.gz ${HOME}/


###
# Run the provision script.
###
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Denver
RUN apt-get update
RUN apt-get install -y tzdata

###
# Custom mpich install.
# Doing it dynamically takes a significant amount of time on Github Actions."
##



###
# Base provision
###

COPY provision_base_ubuntu.sh ${HOME}/
COPY install_mpich.sh ${HOME}/
COPY install_hdf5.sh ${HOME}/
COPY install_intelone.sh ${HOME}/
RUN chmod 755 ${HOME}/provision_base_ubuntu.sh
RUN chmod 755 ${HOME}/install_mpich.sh
RUN chmod 755 ${HOME}/install_hdf5.sh
RUN chmod 755 ${HOME}/install_intelone.sh
RUN apt update
RUN apt install -y dos2unix
RUN dos2unix /root/provision_base_ubuntu.sh
RUN dos2unix /root/install_mpich.sh
RUN dos2unix /root/install_hdf5.sh
RUN dos2unix /root/install_intelone.sh

RUN /bin/sh -x /root/provision_base_ubuntu.sh
RUN sudo bash -x /root/install_mpich.sh -v 4.3.0 -j $(nproc)
## Install system mpich and use that.
#RUN sudo bash -x /root/install_mpich.sh -p 
# Set BITNESS=32 at runtime for linux/386 builds; all other platforms stay at 64.
# The ENTRYPOINT uses 'bash -l' (login shell), which sources /etc/profile.d/*.
# This overrides the ENV BITNESS=64 default above for 386 containers.
ARG TARGETARCH
RUN if [ "${TARGETARCH}" = "386" ]; then \
      printf 'BITNESS=32\nexport BITNESS\n' > /etc/profile.d/bitness.sh; \
    else \
      printf 'BITNESS=64\nexport BITNESS\n' > /etc/profile.d/bitness.sh; \
    fi

#####
# Configure system and environment.
#####
USER ${CUSER}
ENV HOME=/home/${CUSER}
WORKDIR ${HOME}

###
# Add the utility scripts, for portability.
###

COPY run_netcdf_tests.sh ${HOME}/
COPY run_tests.sh ${HOME}/
COPY env_activate.sh ${HOME}/
COPY env_deactivate.sh ${HOME}/
COPY install_mpich.sh ${HOME}/
COPY install_intelone.sh ${HOME}/
COPY install_hdf5.sh ${HOME}/
COPY README.md ${HOME}/
COPY Dockerfile.nctests ${HOME}/

RUN . /etc/profile.d/bitness.sh && echo "Version:\n\tunidata/nctests ($BITNESS) :\t$NCTEST_VERSION\t$(date)" > "/home/tester/${VERSION_FILE}"

USER root
RUN chown -R tester:tester ${HOME}
USER ${CUSER}

RUN dos2unix ${HOME}/run_tests.sh
RUN dos2unix ${HOME}/run_netcdf_tests.sh 
RUN dos2unix ${HOME}/env_activate.sh
RUN dos2unix ${HOME}/env_deactivate.sh
RUN dos2unix ${HOME}/install_mpich.sh
RUN dos2unix ${HOME}/install_hdf5.sh
RUN dos2unix ${HOME}/install_intelone.sh

RUN chmod 755 ${HOME}/run_tests.sh
RUN chmod 755 ${HOME}/run_netcdf_tests.sh
RUN chmod 755 ${HOME}/env_activate.sh
RUN chmod 755 ${HOME}/env_deactivate.sh
RUN chmod 755 ${HOME}/install_mpich.sh
RUN chmod 755 ${HOME}/install_hdf5.sh
RUN chmod 755 ${HOME}/install_intelone.sh



ENTRYPOINT ["/bin/bash", "-l", "-e", "/home/tester/run_tests.sh"]
