FROM unidata/nctests:base

###
# Manually install hdf4 so that we can run
# those tests as well.
###


RUN cd hdf-4.2.12 && ./configure --disable-static --enable-shared --disable-netcdf --disable-fortran --prefix=/usr && make -j 4 && sudo make install
RUN rm -rf hdf-4.2.12


###
# Manually install hdf5 so that we can run
# those tests as well.
###

RUN cd ${HDF5_VER} && ./configure --disable-static --enable-shared --disable-fortran --enable-hl --prefix=/usr --with-szlib && make -j 4 && sudo make install
RUN rm -rf ${HDF5_VER}

###
# Install NCO
###
RUN git clone https://github.com/nco/nco.git --single-branch --branch $NCOBRANCH --depth=1 $NCOBRANCH && mv $NCOBRANCH nco

###
# Copy over the dockerfile, scripts and README.
###

###
# Install NCO for testing here.
###

COPY run_nco_tests.sh ${HOME}/
COPY ncpdq_tst.sh ${HOME}/
COPY in.nc ${HOME}/
COPY foo.nc ${HOME}/
COPY foo_upk.nc ${HOME}/
COPY Dockerfile.nco ${HOME}/

RUN sudo chown -R ${CUSER}:${CUSER} ${HOME}

##
# Run test script on launch.
##
CMD ${HOME}/run_nco_tests.sh
