FROM testsregression_base32

###
# Manually install hdf4 so that we can run
# those tests as well.
###


RUN cd hdf-4.2.11 && ./configure --disable-static --enable-shared --disable-netcdf --disable-fortran --prefix=/usr && make install -j 4
RUN rm -rf hdf-4.2.11


###
# Manually install hdf5 so that we can run
# those tests as well.
###

RUN cd ${HDF5_VER} && ./configure --disable-static --enable-shared --disable-fortran --enable-hl --prefix=/usr && make install -j 4
RUN rm -rf ${HDF5_VER}
###
# Copy over the dockerfile, scripts and README.
###


COPY Dockerfile.serial /root/
# COPY run_serial_tests.sh /root/

##
# Run test script on launch.
##
CMD /root/run_serial_tests.sh
