####
# Common stuff at front.
####
FROM unidata/nctests:serial
MAINTAINER Ward Fisher <wfisher@ucar.edu>
USER root
ENV HOME /root
WORKDIR /root

###
# Define environmental Variables
###

ENV DEBIAN_FRONTEND noninteractive

###
# Install common packages.
###

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y man nano curl git emacs wget gcc g++ gfortran clang gdb autoconf automake make libtool m4 bison flex zlib1g-dev libjpeg-dev libcurl4-openssl-dev python zip elfutils libelf-dev dos2unix cmake


###
# NetCDF-C
###
ENV NCVER=v4.6.2
RUN git clone http://github.com/Unidata/netcdf-c && cd netcdf-c && git checkout ${NCVER} && mkdir build && cd build && cmake .. -DENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr && make -j 4 && make install

###
# Install lvc-maintained abi information.
###
RUN git clone http://github.com/lvc/installer lvc-installer
RUN cd lvc-installer && make install prefix=/usr target=abi-tracker

###
# Copy over some files.
###

COPY run_f_abi_diff.sh /root/
RUN dos2unix /root/run_f_abi_diff.sh

COPY README.md /root/
RUN dos2unix /root/README.md

###
# Run script.
###

CMD /root/run_f_abi_diff.sh
