####
# Common stuff at front.
####
#FROM ubuntu:xenial
FROM docker.unidata.ucar.edu/nctests:serial
MAINTAINER Ward Fisher <wfisher@ucar.edu>
USER root
ENV HOME /root
WORKDIR /root

###
# Define environmental Variables
###


ENV DEBIAN_FRONTEND noninteractive
ENV DIST nc
###
# Install common packages.
###

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y ca-certificates man nano curl git emacs wget gcc g++ gfortran clang gdb autoconf automake make libtool m4 bison flex zlib1g-dev libjpeg-dev libcurl4-openssl-dev python3 zip elfutils libelf-dev dos2unix cmake libzstd-dev libzstd1

###
RUN tar -jxf hdf5-1.12.2.tar.bz2 && cd hdf5-1.12.2 && ./configure --prefix=/usr --disable-static --enable-shared --enable-hl && make -j 4 && make install -j 4

###
ENV NCVER=v4.9.2
RUN git clone https://github.com/Unidata/netcdf-c && cd netcdf-c && git checkout ${NCVER} && mkdir build && cd build && cmake .. -DENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr && make -j 100 && make install
RUN rm -rf netcdf-c


###
# Install lvc-maintained abi information.
# Install abi-dumper individually,
# see https://github.com/lvc/abi-dumper/issues/21
# for more information.
###
RUN git clone http://github.com/lvc/installer lvc-installer
RUN cd lvc-installer && make install prefix=/usr target=abi-tracker
RUN git clone https://github.com/lvc/abi-dumper abi-dumper
RUN cd abi-dumper && make install prefix=/usr

###
# Copy over some files.
###

COPY run_c_abi_diff.sh run_cxx_abi_diff.sh run_f_abi_diff.sh run_abi.sh /root/
RUN dos2unix /root/run_c_abi_diff.sh

COPY README.md /root/
RUN dos2unix /root/README.md

###
# Run script.
###

CMD /root/run_abi.sh
