#####
# Common stuff goes at the front,
# so that we can take advantage of the
# shared layers that docker provides.
#####
#FROM continuumio/miniconda3:4.12.0
#FROM continuumio/miniconda3
FROM ubuntu
USER root
ENV HOME /root
# Where the work takes place
ENV WORKDIR /artifacts
# Where the artifacts end up
ENV ARTDIR /artifacts
WORKDIR ${ARTDIR}
LABEL author="Ward Fisher <wfisher@ucar.edu>"

ENV NCTEST_VERSION 0.1.7 - development

###
# Set up a couple environmental variables.
###

ENV CTEST_OUTPUT_ON_FAILURE 1

## 
# Set default versions
# These can be overridden at runtime, but if they aren't,
# these will be downloaded and installed.
##
ENV H5VER 1.12.2
ENV PNETCDFVER 1.12.3 

##
# Let the user specify the branches.
##
ENV CBRANCH main
ENV FBRANCH main
ENV CXXBRANCH master
ENV PBRANCH master
ENV NCOBRANCH master

##
# Which build systems to run?
##
ENV USEAC TRUE
ENV USECMAKE TRUE

## 
# Compiler and Bitness labels.
##

ENV BITNESS 64
ENV USE_CC gcc
ENV USE_CXX g++

##
# Which tests/systems to run
##
ENV RUNC TRUE
ENV RUNF FALSE
ENV RUNCXX FALSE
ENV RUNP FALSE
ENV RUNNCO FALSE


ENV TESTPROC 1

###
# Copy over files and scripts.
###
COPY run_docker_based_tests.sh ${HOME}/
COPY Dockerfile.netcdf-tests ${HOME}/
COPY README.md ${HOME}/

##
# Install some system packages
##
RUN apt update
RUN apt install -y sudo
RUN apt full-upgrade -y
RUN apt -y install bzip2 g++ gfortran libtool automake autoconf m4 bison flex libcurl4-openssl-dev zlib1g-dev git wget curl libjpeg-dev cmake python3-dev gdb dos2unix antlr libantlr-dev libexpat1-dev libxml2-dev gsl-bin libgsl0-dev udunits-bin libudunits2-0 libudunits2-dev clang zip valgrind make build-essential less unzip patch libsz2 libaec-dev libmpich-dev clang zip

#
# Fiddling around in the system
# 
RUN echo "alias ls='ls --color'" >> ${HOME}/.bashrc

###
# Start conda-based testing
###
WORKDIR ${WORKDIR}
CMD bash -l -e ${HOME}/run_docker_based_tests.sh
