#####
# Common stuff goes at the front,
# so that we can take advantage of the
# shared layers that docker provides.
#####
FROM continuumio/anaconda3
USER root
ENV HOME /root
# Where the work takes place
ENV WORKDIR /working
# Where the artifacts end up
ENV ARTDIR /artifacts
WORKDIR ${ARTDIR}
LABEL author="Ward Fisher <wfisher@ucar.edu>"

ENV NCTEST_VERSION 0.0.1 - development

###
# Set up a couple environmental variables.
###

ENV CTEST_OUTPUT_ON_FAILURE 1

ENV HDF5VER 1.12.2
ENV HDF5_VER hdf5-${HDF5VER}
ENV HDF5_FILE ${HDF5_VER}.tar.bz2
ENV PNCVER 1.11.0

##
# Let the user specify the branches.
##
ENV CBRANCH main
ENV FBRANCH main
ENV CXXBRANCH master
ENV PBRANCH master
ENV NCOBRANCH master

ENV BITNESS 64
ENV USE_CC gcc
ENV USE_CXX g++

ENV RUNC TRUE
ENV RUNF FALSE
ENV RUNCXX FALSE
ENV RUNP FALSE
ENV RUNNCO FALSE

ENV USEDASH FALSE

ENV USEAC FALSE
ENV USECMAKE TRUE

ENV TESTPROC 1

###
# Copy over files and scripts.
###
COPY run_conda_based_tests.sh ${HOME}/
COPY Dockerfile.netcdf-tests ${HOME}/
COPY README.md ${HOME}/

##
# Install some system packages
##
RUN apt update
RUN apt full-upgrade -y
RUN apt install gcc clang mpich libmpich12 doxygen graphviz -y

###
# Start conda-based testing
###
WORKDIR ${WORKDIR}
RUN alias ls='ls --color'
CMD bash -l -e ${HOME}/run_conda_based_tests.sh