#####
# Common stuff goes at the front,
# so that we can take advantage of the
# shared layers that docker provides.
#####
FROM continuumio/miniconda3:4.12.0

USER root
ENV HOME /root
# Where the work takes place
ENV WORKDIR /artifacts
# Where the artifacts end up
ENV ARTDIR /artifacts
WORKDIR ${ARTDIR}
LABEL author="Ward Fisher <wfisher@ucar.edu>"

ENV NCTEST_VERSION 0.1.6 - development

###
# Set up a couple environmental variables.
###

ENV CTEST_OUTPUT_ON_FAILURE 1

ENV HDF5VER 1.12.2
ENV HDF5_VER hdf5-${HDF5VER}
ENV HDF5_FILE ${HDF5_VER}.tar.bz2
ENV PNCVER 1.11.0

##
# Let the user specify the branches.
##
ENV CBRANCH main
ENV FBRANCH main
ENV CXXBRANCH master
ENV PBRANCH master
ENV NCOBRANCH master

##
# Which build systems to run?
##
ENV USEAC TRUE
ENV USECMAKE TRUE

## 
# Compiler and Bitness labels.
##

ENV BITNESS 64
ENV USE_CC gcc
ENV USE_CXX g++

##
# Which tests/systems to run
##
ENV RUNC TRUE
ENV RUNF FALSE
ENV RUNCXX FALSE
ENV RUNP FALSE
ENV RUNNCO FALSE


ENV TESTPROC 1

###
# Copy over files and scripts.
###
COPY run_conda_based_tests.sh ${HOME}/
COPY Dockerfile.netcdf-tests ${HOME}/
COPY README.md ${HOME}/

##
# Install some system packages
##
RUN apt update
RUN apt full-upgrade -y
RUN apt install gcc clang mpich libmpich12 doxygen graphviz -y

#
# Fiddling around in the system
# 
RUN ln -s /bin/sed /usr/bin/sed
RUN echo "alias ls='ls --color'" >> ${HOME}/.bashrc

###
# Start conda-based testing
###
WORKDIR ${WORKDIR}
CMD bash -l -e ${HOME}/run_conda_based_tests.sh
