#####
# Used to generate NetCDF CI docker container.
#####

FROM GENERIC-CONTAINER
MAINTAINER Ward Fisher <wfisher@ucar.edu>

###
# Create a non-root user for running things this.
###
RUN useradd -ms /bin/bash ciuser
RUN echo 'ciuser:ciuser' | chpasswd
ENV HOME /home/ciuser
WORKDIR /home/ciuser

###
# Install Requirements
###
RUN yum -y update
RUN yum -y install m4 git libjpeg-turbo-devel libcurl-devel wget nano libtool bison autoconf curl zlib-devel zip gcc-gfortran gcc-c++ byacc crontabs bzip2 flex make sudo hostname && yum -y clean all

###
# Add ciuser to sudoers.
###
RUN echo "ciuser ALL=NOPASSWD: ALL" >> /etc/sudoers

USER ciuser

###
# Build and install cmake, hdf4/hdf5.
###

###
# CMake stuff, to ensure we have an
# appropriate version.
###
ENV CMAKE_VER cmake-3.6.1
ENV CMAKE_FILE ${CMAKE_VER}.tar.gz
RUN wget http://www.cmake.org/files/v3.6/${CMAKE_FILE}
RUN tar -zxf ${CMAKE_FILE}

USER root
RUN cd ${CMAKE_VER} && ./configure --prefix=/usr && make install -j 2 && ldconfig
RUN rm -rf ${CMAKE_VER}

USER ciuser
##
# HDF4
##
ENV HDF4_VER hdf-4.2.12
ENV HDF4_FILE ${HDF4_VER}.tar.bz2
RUN wget http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/${HDF4_FILE}

RUN tar -jxf ${HDF4_FILE}
USER root

RUN cd ${HDF4_VER} && ./configure --disable-static --enable-shared --disable-netcdf --disable-fortran --prefix=/usr && make install -j 2
RUN rm -rf /home/ciuser/${HDF4_VER}

USER ciuser
##
# HDF5
##
ENV HDF5VER 1.8.19
ENV HDF5_VER hdf5-${HDF5VER}
ENV HDF5_FILE ${HDF5_VER}.tar.bz2

RUN wget http://www.hdfgroup.org/ftp/HDF5/releases/${HDF5_VER}/src/${HDF5_FILE}
RUN tar -jxf ${HDF5_FILE}
USER root

RUN cd ${HDF5_VER} && ./configure --disable-static --enable-shared --disable-fortran --enable-hl --prefix=/usr && make install -j 2

RUN rm -rf /home/ciuser/${HDF5_VER}
USER ciuser

###
# NetCDF for fortran, cxx stuff.
###
RUN git clone git://github.com/Unidata/netcdf-c
USER root
RUN ldconfig
RUN cd netcdf-c && autoreconf -if && ./configure --prefix=/home/ciuser/local2 && make install -j 2
RUN rm -rf /home/ciuser/netcdf-c
USER ciuser


###
# Do some final cleanup
###
USER root
RUN yum clean all
USER ciuser

###
# Set Timezone
###
USER root
ENV TZ America/Denver
RUN ln -snf /usr/share/timezone/$TZ /etc/localtime && echo $TZ > /etc/timezone
USER ciuser

###
# Copy over some files.
###
ADD run_all_ci_images.sh /home/ciuser/
ADD squash_all_ci_images.sh /home/ciuser/
ADD push_all_ci_images.sh /home/ciuser/
ADD crontab.in.serial /home/ciuser/
RUN mv /home/ciuser/crontab.in.serial /home/ciuser/crontab.in

ADD shell-scripts/run_nightly_test.sh /home/ciuser/

ADD cmake-scripts/CI.cmake /home/ciuser/
ADD cmake-scripts/CTestConfig.cmake /home/ciuser/
ADD cmake-scripts/FCI.cmake /home/ciuser/
ADD cmake-scripts/CXX4I.cmake /home/ciuser/
ADD cmake-scripts/FPARCI.cmake /home/ciuser/
ADD cmake-scripts/PARCI.cmake /home/ciuser/
ADD cmake-scripts/ctest_service.serial.sh /home/ciuser/
ADD cmake-scripts/ctest_service.parallel.sh /home/ciuser/
###
# Install crontab
###
RUN crontab < /home/ciuser/crontab.in
RUN mv /home/ciuser/crontab.in /home/ciuser/.cron.lock

###
# Final Command
###
CMD /home/ciuser/ctest_service.serial.sh
